<html>
<head>
    <title>Смутные Времена - Онлайн игра</title>
    <meta charset="windows-1251">
    <link rel='stylesheet' href='/styles/brown/main.css'>
</head>
<body>
    <table width='100%' id='main'>
        <tr>
            <td align='right' width='50%'>
                <img src='/styles/brown/images/main_logo.jpg'/ width='450'>
            </td>
            <td align='left' width='50%' valign='top'>
                <form name='login' method='get' action='/vr/login/'>
                    <table>
                        <tr>
                            <td>Имя:</td>
                            <td>
                                <input type='text' name='login'>
                            </td>
                        </tr>
                        <tr>
                            <td>Пароль:</td>
                            <td>
                                <input type='password' name='password'>
                            </td>
                        </tr>
                    </table>
                    <input type='submit' value='Войти'>
                </form>
                <div><a href='/vr/register/'>Регистрация</a></div>
                <div><a href='/vr/recovery/'>Забыли пароль?</a></div>
            </td>
        </tr>
    </table>
</body>
</html>
